<?php
//-- 配役設定 --//
class ChaosConfig {
  //-- 固定枠 --//
  //闇鍋
  public static $chaos_fix_role_list		= ['mage' => 1, 'wolf' => 1];

  //真・闇鍋
  public static $chaosfull_fix_role_list	= ['mage' => 1, 'wolf' => 1];

  //超・闇鍋
  public static $chaos_hyper_fix_role_list	= ['mage' => 1, 'wolf' => 1];

  //裏・闇鍋
  public static $chaos_verso_fix_role_list	= [];

  //-- 配役テーブル --//
  //人狼の最小出現枠 (役職名 => 出現比)
  //闇鍋
  public static $chaos_wolf_list = [
    'wolf'        => 60,
    'boss_wolf'   =>  5,
    'poison_wolf' => 10,
    'tongue_wolf' =>  5,
    'silver_wolf' => 20
  ];

  //真・闇鍋
  public static $chaosfull_wolf_list = [
    'wolf'        => 60,
    'boss_wolf'   =>  5,
    'cursed_wolf' =>  5,
    'poison_wolf' =>  5,
    'resist_wolf' =>  5,
    'tongue_wolf' =>  5,
    'cute_wolf'   => 10,
    'silver_wolf' =>  5
  ];

  //超・闇鍋
  public static $chaos_hyper_wolf_list = [
    'wolf'              => 15,
    'boss_wolf'         =>  1,
    'mist_wolf'         =>  2,
    'tiger_wolf'        =>  2,
    'gold_wolf'         =>  2,
    'phantom_wolf'      =>  2,
    'cursed_wolf'       =>  1,
    'quiet_wolf'        =>  1,
    'wise_wolf'         =>  3,
    'sweet_wolf'        =>  1,
    'eye_wolf'          =>  1,
    'disguise_wolf'     =>  2,
    'purple_wolf'       =>  2,
    'snow_wolf'         =>  2,
    'miasma_wolf'       =>  1,
    'homogeneous_wolf'  =>  1,
    'heterologous_wolf' =>  1,
    'ascetic_wolf'      =>  1,
    'fortitude_wolf'    =>  2,
    'poison_wolf'       =>  3,
    'resist_wolf'       =>  2,
    'revive_wolf'       =>  2,
    'trap_wolf'         =>  2,
    'fire_wolf'         =>  2,
    'thorn_wolf'        =>  1,
    'step_wolf'         =>  1,
    'blue_wolf'         =>  2,
    'emerald_wolf'      =>  2,
    'decieve_wolf'      =>  2,
    'doom_wolf'         =>  2,
    'sex_wolf'          =>  2,
    'honey_wolf'        =>  1,
    'sharp_wolf'        =>  1,
    'hungry_wolf'       =>  1,
    'spell_wolf'        =>  1,
    'tongue_wolf'       =>  1,
    'possessed_wolf'    =>  1,
    'sirius_wolf'       =>  1,
    'elder_wolf'        =>  3,
    'cute_wolf'         =>  7,
    'scarlet_wolf'      =>  3,
    'silver_wolf'       =>  9,
    'emperor_wolf'      =>  5
  ];

  //妖狐の最小出現枠 (役職名 => 出現比)
  //闇鍋
  public static $chaos_fox_list = [
    'fox'       => 90,
    'child_fox' => 10
  ];

  //真・闇鍋
  public static $chaosfull_fox_list = [
    'fox'        => 80,
    'white_fox'  =>  3,
    'poison_fox' =>  3,
    'voodoo_fox' =>  3,
    'cursed_fox' =>  3,
    'silver_fox' =>  3,
    'child_fox'  =>  5
  ];

  //超・闇鍋
  public static $chaos_hyper_fox_list = [
    'fox'            => 18,
    'white_fox'      =>  2,
    'black_fox'      =>  2,
    'mist_fox'       =>  2,
    'tiger_fox'      =>  2,
    'gold_fox'       =>  2,
    'phantom_fox'    =>  2,
    'purple_fox'     =>  2,
    'sweet_fox'      =>  2,
    'snow_fox'       =>  3,
    'fortitude_fox'  =>  2,
    'poison_fox'     =>  3,
    'blue_fox'       =>  2,
    'spell_fox'      =>  2,
    'sacrifice_fox'  =>  2,
    'emerald_fox'    =>  2,
    'voodoo_fox'     =>  2,
    'step_fox'       =>  2,
    'revive_fox'     =>  2,
    'possessed_fox'  =>  2,
    'doom_fox'       =>  2,
    'trap_fox'       =>  2,
    'cursed_fox'     =>  2,
    'elder_fox'      =>  3,
    'cute_fox'       =>  5,
    'scarlet_fox'    =>  3,
    'silver_fox'     =>  3,
    'immolate_fox'   =>  2,
    'child_fox'      =>  4,
    'sex_fox'        =>  2,
    'stargazer_fox'  =>  2,
    'jammer_fox'     =>  2,
    'monk_fox'       =>  2,
    'miasma_fox'     =>  2,
    'howl_fox'       =>  2,
    'vindictive_fox' =>  2,
    'critical_fox'   =>  2
  ];

  //ランダム配役テーブル (役職名 => 出現比)
  //闇鍋
  public static $chaos_random_role_list = [
    'human'           => 88,
    'mage'            => 50,
    'soul_mage'       =>  5,
    'psycho_mage'     => 10,
    'necromancer'     => 60,
    'medium'          => 30,
    'guard'           => 70,
    'poison_guard'    =>  5,
    'reporter'        => 15,
    'common'          => 75,
    'poison'          => 40,
    'incubate_poison' => 10,
    'pharmacist'      => 20,
    'assassin'        => 20,
    'doll'            => 20,
    'doll_master'     => 10,
    'escaper'         => 30,
    'wolf'            => 80,
    'boss_wolf'       => 10,
    'poison_wolf'     => 40,
    'tongue_wolf'     => 20,
    'silver_wolf'     => 30,
    'mad'             => 60,
    'fanatic_mad'     => 20,
    'whisper_mad'     => 10,
    'fox'             => 50,
    'child_fox'       => 20,
    'cupid'           => 30,
    'self_cupid'      => 10,
    'quiz'            =>  2,
    'chiroptera'      => 50,
    'mania'           => 10
  ];

  //真・闇鍋
  public static $chaosfull_random_role_list = [
    'human'              =>  3,
    'suspect'            => 15,
    'unconscious'        => 20,
    'mage'               => 20,
    'soul_mage'          =>  5,
    'psycho_mage'        => 10,
    'sex_mage'           => 15,
    'voodoo_killer'      => 10,
    'dummy_mage'         => 15,
    'necromancer'        => 40,
    'soul_necromancer'   =>  5,
    'yama_necromancer'   => 10,
    'dummy_necromancer'  => 25,
    'medium'             => 30,
    'guard'              => 40,
    'poison_guard'       =>  5,
    'reporter'           => 10,
    'anti_voodoo'        => 15,
    'dummy_guard'        => 20,
    'common'             => 80,
    'dummy_common'       => 10,
    'poison'             => 20,
    'strong_poison'      =>  5,
    'incubate_poison'    => 10,
    'dummy_poison'       => 15,
    'poison_cat'         => 10,
    'pharmacist'         => 30,
    'assassin'           => 20,
    'mind_scanner'       => 20,
    'jealousy'           => 15,
    'wolf'               => 75,
    'boss_wolf'          => 10,
    'cursed_wolf'        => 10,
    'poison_wolf'        => 15,
    'resist_wolf'        => 15,
    'tongue_wolf'        => 20,
    'cute_wolf'          => 30,
    'silver_wolf'        => 15,
    'mad'                => 20,
    'fanatic_mad'        => 10,
    'whisper_mad'        =>  5,
    'jammer_mad'         => 10,
    'voodoo_mad'         => 10,
    'dream_eater_mad'    => 10,
    'trap_mad'           => 10,
    'corpse_courier_mad' => 15,
    'fox'                => 30,
    'white_fox'          => 10,
    'poison_fox'         =>  7,
    'voodoo_fox'         =>  5,
    'cursed_fox'         =>  3,
    'silver_fox'         =>  5,
    'child_fox'          => 10,
    'cupid'              => 25,
    'self_cupid'         => 10,
    'mind_cupid'         =>  5,
    'quiz'               =>  2,
    'chiroptera'         => 20,
    'poison_chiroptera'  =>  5,
    'cursed_chiroptera'  =>  5,
    'mania'              => 20,
    'unknown_mania'      => 10
  ];

  //超・闇鍋
  public static $chaos_hyper_random_role_list = [
    'human'                 =>   1,
    'saint'                 =>  12,
    'executor'              =>   9,
    'elder'                 =>  20,
    'scripter'              =>  10,
    'eccentricer'           =>  10,
    'tough'                 =>   9,
    'prince'                =>   9,
    'suspect'               =>  20,
    'unconscious'           =>  20,
    'mage'                  => 100,
    'puppet_mage'           =>  40,
    'step_mage'             =>  25,
    'critical_mage'         =>  30,
    'soul_mage'             =>  20,
    'psycho_mage'           =>  60,
    'sex_mage'              =>  40,
    'stargazer_mage'        =>  40,
    'voodoo_killer'         =>  90,
    'cute_mage'             =>  35,
    'dummy_mage'            =>  70,
    'necromancer'           => 100,
    'soul_necromancer'      =>  20,
    'psycho_necromancer'    =>  65,
    'embalm_necromancer'    =>  60,
    'emissary_necromancer'  =>  30,
    'attempt_necromancer'   =>  60,
    'yama_necromancer'      =>  90,
    'dummy_necromancer'     =>  75,
    'medium'                =>  60,
    'bacchus_medium'        =>  45,
    'seal_medium'           =>  35,
    'revive_medium'         =>  25,
    'eclipse_medium'        =>  35,
    'priest'                =>  40,
    'bishop_priest'         =>  30,
    'dowser_priest'         =>  20,
    'weather_priest'        =>  20,
    'high_priest'           =>  20,
    'crisis_priest'         =>  30,
    'widow_priest'          =>  25,
    'holy_priest'           =>  20,
    'revive_priest'         => 100,
    'border_priest'         =>  20,
    'dummy_priest'          =>  25,
    'guard'                 => 120,
    'hunter_guard'          =>  90,
    'blind_guard'           =>  25,
    'finder_guard'          =>  30,
    'gatekeeper_guard'      =>  30,
    'step_guard'            =>  30,
    'grave_guard'           =>  30,
    'wanderer_guard'        =>  30,
    'reflect_guard'         =>  30,
    'poison_guard'          =>  20,
    'fend_guard'            =>  25,
    'reporter'              => 100,
    'anti_voodoo'           => 150,
    'elder_guard'           =>  60,
    'dummy_guard'           =>  80,
    'common'                => 250,
    'leader_common'         =>  35,
    'detective_common'      =>  40,
    'trap_common'           =>  60,
    'sacrifice_common'      =>  50,
    'ghost_common'          =>  25,
    'spell_common'          =>  30,
    'critical_common'       =>  40,
    'hermit_common'         =>  70,
    'dummy_common'          => 150,
    'poison'                => 120,
    'strong_poison'         =>  30,
    'incubate_poison'       =>  80,
    'guide_poison'          =>  60,
    'snipe_poison'          =>  60,
    'chain_poison'          =>  60,
    'dummy_poison'          =>  90,
    'poison_cat'            =>  40,
    'revive_cat'            =>  16,
    'sacrifice_cat'         =>  20,
    'doom_cat'              =>  18,
    'missfire_cat'          =>  18,
    'fetish_cat'            =>  18,
    'eclipse_cat'           =>  20,
    'pharmacist'            =>  60,
    'cure_pharmacist'       =>  40,
    'revive_pharmacist'     =>  30,
    'alchemy_pharmacist'    =>  30,
    'centaurus_pharmacist'  =>  40,
    'assassin'              =>  25,
    'doom_assassin'         =>  18,
    'select_assassin'       =>  16,
    'step_assassin'         =>  12,
    'sweep_assassin'        =>  12,
    'professional_assassin' =>  12,
    'ascetic_assassin'      =>  15,
    'reverse_assassin'      =>  12,
    'soul_assassin'         =>  10,
    'eclipse_assassin'      =>  18,
    'mind_scanner'          =>  25,
    'evoke_scanner'         =>  18,
    'presage_scanner'       =>  15,
    'step_scanner'          =>  12,
    'clairvoyance_scanner'  =>  10,
    'eye_scanner'           =>  18,
    'whisper_scanner'       =>  14,
    'howl_scanner'          =>  14,
    'telepath_scanner'      =>  14,
    'dummy_scanner'         =>  20,
    'jealousy'              =>  30,
    'divorce_jealousy'      =>  18,
    'flower_jealousy'       =>   6,
    'priest_jealousy'       =>  20,
    'poison_jealousy'       =>  14,
    'miasma_jealousy'       =>  12,
    'critical_jealousy'     =>  20,
    'brownie'               =>  20,
    'thunder_brownie'       =>  14,
    'echo_brownie'          =>  10,
    'revive_brownie'        =>  14,
    'harvest_brownie'       =>  12,
    'maple_brownie'         =>  12,
    'cursed_brownie'        =>  10,
    'sun_brownie'           =>  10,
    'history_brownie'       =>  10,
    'barrier_brownie'       =>   8,
    'wizard'                =>  16,
    'soul_wizard'           =>   6,
    'pierrot_wizard'        =>   8,
    'esper_wizard'          =>  10,
    'awake_wizard'          =>  10,
    'mimic_wizard'          =>  10,
    'plural_wizard'         =>   8,
    'spark_wizard'          =>   8,
    'spiritism_wizard'      =>  12,
    'philosophy_wizard'     =>  10,
    'barrier_wizard'        =>  10,
    'astray_wizard'         =>  12,
    'doll'                  =>  50,
    'friend_doll'           =>  30,
    'phantom_doll'          =>  20,
    'poison_doll'           =>  20,
    'doom_doll'             =>  20,
    'revive_doll'           =>  20,
    'scarlet_doll'          =>  20,
    'silver_doll'           =>  20,
    'doll_master'           =>  40,
    'toy_doll_master'       =>  30,
    'revive_doll_master'    =>  20,
    'serve_doll_master'     =>  10,
    'escaper'               =>  25,
    'psycho_escaper'        =>  18,
    'incubus_escaper'       =>  16,
    'succubus_escaper'      =>  16,
    'doom_escaper'          =>  10,
    'agent_escaper'         =>  12,
    'divine_escaper'        =>   8,
    'stargazer_escaper'     =>  15,
    'wolf'                  => 150,
    'boss_wolf'             =>  20,
    'mist_wolf'             =>  30,
    'tiger_wolf'            =>  30,
    'gold_wolf'             =>  30,
    'phantom_wolf'          =>  35,
    'cursed_wolf'           =>  30,
    'quiet_wolf'            =>  30,
    'wise_wolf'             => 100,
    'sweet_wolf'            =>  30,
    'eye_wolf'              =>  25,
    'disguise_wolf'         =>  25,
    'purple_wolf'           =>  30,
    'snow_wolf'             =>  30,
    'miasma_wolf'           =>  20,
    'homogeneous_wolf'      =>  20,
    'heterologous_wolf'     =>  20,
    'ascetic_wolf'          =>  30,
    'fortitude_wolf'        =>  30,
    'poison_wolf'           => 150,
    'resist_wolf'           => 100,
    'revive_wolf'           =>  30,
    'trap_wolf'             =>  20,
    'fire_wolf'             =>  30,
    'thorn_wolf'            =>  20,
    'step_wolf'             =>  25,
    'blue_wolf'             =>  30,
    'emerald_wolf'          =>  30,
    'decieve_wolf'          =>  25,
    'doom_wolf'             =>  35,
    'sex_wolf'              =>  40,
    'honey_wolf'            =>  25,
    'sharp_wolf'            =>  25,
    'hungry_wolf'           =>  50,
    'spell_wolf'            =>  25,
    'tongue_wolf'           =>  25,
    'possessed_wolf'        =>  20,
    'sirius_wolf'           =>  20,
    'elder_wolf'            =>  50,
    'cute_wolf'             => 100,
    'scarlet_wolf'          =>  70,
    'silver_wolf'           =>  90,
    'emperor_wolf'          =>  50,
    'mad'                   =>  70,
    'fanatic_mad'           =>  25,
    'whisper_mad'           =>  20,
    'swindle_mad'           =>  25,
    'plural_mad'            =>  30,
    'jammer_mad'            =>  50,
    'voodoo_mad'            =>  40,
    'enchant_mad'           =>  30,
    'seiren_mad'            =>  25,
    'step_mad'              =>  30,
    'dream_eater_mad'       =>  50,
    'possessed_mad'         =>  25,
    'grave_mad'             =>  30,
    'rioter_mad'            =>  30,
    'trap_mad'              =>  35,
    'snow_trap_mad'         =>  30,
    'corpse_courier_mad'    =>  50,
    'amaze_mad'             =>  30,
    'agitate_mad'           =>  30,
    'miasma_mad'            =>  25,
    'critical_mad'          =>  25,
    'fire_mad'              =>  30,
    'follow_mad'            =>  25,
    'therian_mad'           =>  40,
    'revive_mad'            =>  30,
    'spy_mad'               =>  25,
    'immolate_mad'          =>  45,
    'fox'                   =>  35,
    'white_fox'             =>   8,
    'black_fox'             =>   8,
    'mist_fox'              =>  12,
    'tiger_fox'             =>  12,
    'gold_fox'              =>  12,
    'phantom_fox'           =>  10,
    'purple_fox'            =>  10,
    'sweet_fox'             =>   8,
    'snow_fox'              =>  12,
    'fortitude_fox'         =>  12,
    'poison_fox'            =>  15,
    'blue_fox'              =>  12,
    'spell_fox'             =>  12,
    'sacrifice_fox'         =>  12,
    'emerald_fox'           =>  12,
    'voodoo_fox'            =>  10,
    'step_fox'              =>  12,
    'revive_fox'            =>  12,
    'possessed_fox'         =>  12,
    'doom_fox'              =>   8,
    'trap_fox'              =>   8,
    'cursed_fox'            =>   6,
    'elder_fox'             =>  15,
    'cute_fox'              =>  15,
    'scarlet_fox'           =>  15,
    'silver_fox'            =>  15,
    'immolate_fox'          =>  20,
    'child_fox'             =>  28,
    'sex_fox'               =>  18,
    'stargazer_fox'         =>  18,
    'jammer_fox'            =>  12,
    'monk_fox'              =>  14,
    'miasma_fox'            =>  16,
    'howl_fox'              =>  16,
    'vindictive_fox'        =>  14,
    'critical_fox'          =>  14,
    'depraver'              =>  40,
    'fire_depraver'         =>  20,
    'tailtip_depraver'      =>  15,
    'sacrifice_depraver'    =>  10,
    'silver_depraver'       =>  15,
    'cupid'                 =>  25,
    'self_cupid'            =>  18,
    'moon_cupid'            =>  10,
    'altair_cupid'          =>  10,
    'sacrifice_cupid'       =>   8,
    'mind_cupid'            =>  14,
    'sweet_cupid'           =>  12,
    'letter_cupid'          =>  10,
    'minstrel_cupid'        =>   6,
    'triangle_cupid'        =>  12,
    'nephila_cupid'         =>  10,
    'revive_cupid'          =>  10,
    'snow_cupid'            =>  15,
    'angel'                 =>  30,
    'rose_angel'            =>  20,
    'lily_angel'            =>  20,
    'exchange_angel'        =>  12,
    'ark_angel'             =>  12,
    'sacrifice_angel'       =>   8,
    'scarlet_angel'         =>  18,
    'cursed_angel'          =>  20,
    'quiz'                  =>  20,
    'vampire'               =>  18,
    'poison_vampire'        =>  14,
    'follow_vampire'        =>  10,
    'incubus_vampire'       =>  10,
    'succubus_vampire'      =>  10,
    'homogeneous_vampire'   =>  12,
    'heterologous_vampire'  =>  12,
    'passion_vampire'       =>  12,
    'step_vampire'          =>  12,
    'doom_vampire'          =>   8,
    'sacrifice_vampire'     =>   8,
    'soul_vampire'          =>   6,
    'scarlet_vampire'       =>  18,
    'chiroptera'            =>  36,
    'poison_chiroptera'     =>  17,
    'follow_chiroptera'     =>  15,
    'cursed_chiroptera'     =>  17,
    'boss_chiroptera'       =>  10,
    'elder_chiroptera'      =>  12,
    'cute_chiroptera'       =>  25,
    'doom_chiroptera'       =>  12,
    'scarlet_chiroptera'    =>  18,
    'dummy_chiroptera'      =>  15,
    'fairy'                 =>  10,
    'spring_fairy'          =>   7,
    'summer_fairy'          =>   7,
    'autumn_fairy'          =>   7,
    'winter_fairy'          =>   7,
    'flower_fairy'          =>   6,
    'star_fairy'            =>   6,
    'sun_fairy'             =>   6,
    'moon_fairy'            =>   6,
    'grass_fairy'           =>   6,
    'light_fairy'           =>   6,
    'dark_fairy'            =>   6,
    'shadow_fairy'          =>   6,
    'greater_fairy'         =>   6,
    'mirror_fairy'          =>   6,
    'sweet_fairy'           =>   6,
    'gender_fairy'          =>   6,
    'chill_fairy'           =>   5,
    'ice_fairy'             =>   5,
    'ogre'                  =>  12,
    'orange_ogre'           =>   9,
    'indigo_ogre'           =>   9,
    'cow_ogre'              =>   7,
    'horse_ogre'            =>   7,
    'poison_ogre'           =>   9,
    'west_ogre'             =>   6,
    'east_ogre'             =>   6,
    'north_ogre'            =>   6,
    'south_ogre'            =>   6,
    'incubus_ogre'          =>   8,
    'wise_ogre'             =>   8,
    'collector_ogre'        =>   8,
    'power_ogre'            =>   6,
    'revive_ogre'           =>   8,
    'sacrifice_ogre'        =>   5,
    'yaksa'                 =>  12,
    'betray_yaksa'          =>  10,
    'cursed_yaksa'          =>  10,
    'succubus_yaksa'        =>  10,
    'hariti_yaksa'          =>  10,
    'vajra_yaksa'           =>  10,
    'power_yaksa'           =>  10,
    'dowser_yaksa'          =>   8,
    'duelist'               =>   8,
    'valkyrja_duelist'      =>   6,
    'critical_duelist'      =>   4,
    'cowboy_duelist'        =>   6,
    'triangle_duelist'      =>   5,
    'triphase_duelist'      =>   5,
    'doom_duelist'          =>   5,
    'perverse_duelist'      =>   5,
    'sea_duelist'           =>   6,
    'avenger'               =>  10,
    'poison_avenger'        =>   6,
    'cursed_avenger'        =>   6,
    'critical_avenger'      =>   8,
    'trick_avenger'         =>   3,
    'foughten_avenger'      =>   6,
    'revive_avenger'        =>   4,
    'cute_avenger'          =>   7,
    'patron'                =>  12,
    'soul_patron'           =>   7,
    'sacrifice_patron'      =>   6,
    'shepherd_patron'       =>   8,
    'plumage_patron'        =>   7,
    'critical_patron'       =>  10,
    'tengu'                 =>  25,
    'soul_tengu'            =>  10,
    'passion_tengu'         =>  20,
    'meteor_tengu'          =>  15,
    'involve_tengu'         =>  12,
    'priest_tengu'          =>  18,
    'eclipse_tengu'         =>  20,
    'mania'                 =>  65,
    'trick_mania'           =>  20,
    'basic_mania'           =>  20,
    'scarlet_mania'         =>  15,
    'soul_mania'            =>  10,
    'dummy_mania'           =>  10,
    'unknown_mania'         =>  14,
    'wirepuller_mania'      =>   8,
    'fire_mania'            =>   8,
    'sacrifice_mania'       =>   5,
    'resurrect_mania'       =>   5,
    'revive_mania'          =>   5,
    'lute_mania'            =>   5,
    'harp_mania'            =>   5,
    'mask_mania'            =>   5
  ];

  //裏・闇鍋
  public static $chaos_verso_random_role_list = [
    'human'       => 14,
    'mage'        => 10,
    'necromancer' => 10,
    'guard'       =>  5,
    'common'      => 10,
    'poison'      =>  5,
    'assassin'    =>  5,
    'wolf'        => 20,
    'mad'         => 10,
    'fanatic_mad' =>  5,
    'fox'         =>  5,
    'quiz'        =>  1
  ];

  //村人から振り返る役職 => 出現比
  //闇鍋
  public static $chaos_replace_human_role_list		= ['mania' => 1];

  //真・闇鍋
  public static $chaosfull_replace_human_role_list	= ['mania' => 7, 'unknown_mania' => 3];

  //超・闇鍋
  public static $chaos_hyper_replace_human_role_list	= [
    'mania'            => 15,
    'trick_mania'      => 12,
    'basic_mania'      => 12,
    'scarlet_mania'    =>  9,
    'soul_mania'       =>  7,
    'dummy_mania'      =>  5,
    'unknown_mania'    =>  8,
    'wirepuller_mania' =>  6,
    'fire_mania'       =>  5,
    'sacrifice_mania'  =>  3,
    'resurrect_mania'  =>  3,
    'revive_mania'     =>  3,
    'lute_mania'       =>  4,
    'harp_mania'       =>  4,
    'mask_mania'       =>  4
  ];

  //-- 出現補正値 --//
  public static $min_wolf_rate  = 10; //人狼の最小出現比 (総人口 / N)
  public static $min_fox_rate   = 15; //妖狐の最小出現比 (総人口 / N)
  public static $max_human_rate = 10; //村人の最大出現比 (総人口 / N)

  //役職グループの最大出現比 (グループ => 総人口 / N)
  public static $role_group_rate_list = [
    CampGroup::MAGE         =>  6.2,
    CampGroup::NECROMANCER  =>  6.2,
    CampGroup::MEDIUM       =>  6.2,
    CampGroup::PRIEST       =>  7.1,
    CampGroup::GUARD        =>  7.1,
    CampGroup::COMMON       =>  7.1,
    CampGroup::POISON       =>  7.1,
    CampGroup::POISON_CAT   => 10,
    CampGroup::PHARMACIST   =>  7.1,
    CampGroup::ASSASSIN     =>  9,
    CampGroup::MIND_SCANNER =>  7.1,
    CampGroup::JEALOUSY     =>  8,
    CampGroup::BROWNIE      =>  8,
    CampGroup::WIZARD       =>  9,
    CampGroup::DOLL         =>  7.1,
    CampGroup::ESCAPER      =>  7.1,
    CampGroup::WOLF         =>  4.8,
    CampGroup::MAD          =>  7.1,
    CampGroup::FOX          => 10,
    CampGroup::CHILD_FOX    => 14.2,
    CampGroup::DEPRAVER     => 16.1,
    CampGroup::CUPID        => 10,
    CampGroup::ANGEL        => 12,
    CampGroup::QUIZ         =>  8,
    CampGroup::VAMPIRE      =>  8,
    CampGroup::CHIROPTERA   =>  8,
    CampGroup::FAIRY        =>  9,
    CampGroup::OGRE         =>  9,
    CampGroup::YAKSA        => 12,
    CampGroup::DUELIST      => 15.0,
    CampGroup::AVENGER      => 16.1,
    CampGroup::PATRON       => 15.0,
    CampGroup::TENGU        => 12
  ];

  //-- 固定配役追加モード --//
  /*
    fix    : 固定枠
    random : ランダム枠 (各配列の中身は役職 => 出現比)
    count  : ランダム出現数 (ランダム枠毎の出現数)

    例)
    doll_master が +1, [doll:poison_doll = 2:1] の割合でランダムに +1,
    [scarlet_doll:silver_doll = 5:1] の割合でランダムに +2
    'a' => ['fix'    => ['doll_master' => 1],
	    'random' => [['doll'  => 2, 'poison_doll' => 1],
			 ['scarlet_doll' => 5, 'silver_doll' => 1]],
	     'count'  => [1, 2]],
  */
  public static $topping_list = [
    'a' => ['random' => [['doll'         => 30,
			  'friend_doll'  =>  5,
			  'phantom_doll' => 10,
			  'poison_doll'  => 15,
			  'doom_doll'    => 15,
			  'revive_doll'  => 10,
			  'scarlet_doll' => 10,
			  'silver_doll'  =>  5],
			 ['doll_master'        => 40,
			  'toy_doll_master'    => 30,
			  'revive_doll_master' => 20,
			  'serve_doll_master'  => 10],
			 ['puppet_mage'        => 15,
			  'scarlet_doll'       =>  5,
			  'scarlet_wolf'       => 25,
			  'scarlet_fox'        => 15,
			  'scarlet_angel'      => 15,
			  'scarlet_vampire'    => 10,
			  'scarlet_chiroptera' => 10,
			  'scarlet_mania'      =>  5]],
	    'count'  => [1, 1, 1]],
    'b' => ['fix'    => ['quiz' => 1, 'poison_ogre' => 1]],
    'c' => ['random' => [['vampire'              => 12,
			  'poison_vampire'       => 10,
			  'follow_vampire'       =>  8,
			  'incubus_vampire'      =>  6,
			  'succubus_vampire'     =>  6,
			  'homogeneous_vampire'  =>  8,
			  'heterologous_vampire' =>  8,
			  'passion_vampire'      =>  9,
			  'step_vampire'         =>  8,
			  'doom_vampire'         =>  6,
			  'sacrifice_vampire'    =>  6,
			  'soul_vampire'         =>  3,
			  'scarlet_vampire'      => 10],
			 ['mist_wolf'       => 60,
			  'mist_fox'        => 30,
			  'boss_chiroptera' => 10]],
	    'count' => [1, 1]],
    'd' => ['random' => [['poison_cat'    => 3,
			  'revive_cat'    => 1,
			  'sacrifice_cat' => 1,
			  'doom_cat'      => 1,
			  'missfire_cat'  => 1,
			  'fetish_cat'    => 1,
			  'eclipse_cat'   => 2],
			 ['grave_mad' => 1,
			  'rioter_mad' => 1]],
	    'count'  => [1, 1]],
    'e' => ['fix' => ['anti_voodoo' => 1, 'possessed_wolf' => 1]],
    'f' => ['random' => [['ogre'           => 8,
			  'orange_ogre'    => 5,
			  'indigo_ogre'    => 5,
			  'cow_ogre'       => 3,
			  'horse_ogre'     => 3,
			  'poison_ogre'    => 3,
			  'west_ogre'      => 3,
			  'east_ogre'      => 3,
			  'north_ogre'     => 3,
			  'south_ogre'     => 3,
			  'incubus_ogre'   => 3,
			  'wise_ogre'      => 5,
			  'collector_ogre' => 4,
			  'power_ogre'     => 4,
			  'revive_ogre'    => 4,
			  'sacrifice_ogre' => 3,
			  'yaksa'          => 7,
			  'betray_yaksa'   => 5,
			  'cursed_yaksa'   => 5,
			  'succubus_yaksa' => 3,
			  'hariti_yaksa'   => 5,
			  'vajra_yaksa'    => 5,
			  'power_yaksa'    => 5,
			  'dowser_yaksa'   => 3]],
	    'count' => [2]],
    'g' => ['random' => [['mad'                => 5,
			  'fanatic_mad'        => 3,
			  'whisper_mad'        => 2,
			  'swindle_mad'        => 3,
			  'jammer_mad'         => 4,
			  'voodoo_mad'         => 4,
			  'enchant_mad'        => 5,
			  'seiren_mad'         => 4,
			  'step_mad'           => 4,
			  'dream_eater_mad'    => 5,
			  'possessed_mad'      => 4,
			  'grave_mad'          => 3,
			  'rioter_mad'         => 3,
			  'trap_mad'           => 3,
			  'snow_trap_mad'      => 3,
			  'corpse_courier_mad' => 5,
			  'amaze_mad'          => 4,
			  'agitate_mad'        => 4,
			  'miasma_mad'         => 4,
			  'critical_mad'       => 4,
			  'fire_mad'           => 4,
			  'follow_mad'         => 4,
			  'therian_mad'        => 5,
			  'revive_mad'         => 4,
			  'spy_mad'            => 4,
			  'immolate_mad'       => 4],
			 ['suspect'           => 1,
			  'unconscious'       => 1,
			  'dummy_mage'        => 1,
			  'dummy_necromancer' => 1,
			  'dummy_priest'      => 1,
			  'dummy_guard'       => 1,
			  'dummy_common'      => 1,
			  'dummy_poison'      => 1,
			  'dummy_scanner'     => 1,
			  'dummy_chiroptera'  => 1,
			  'dummy_mania'       => 1],
			 ['psycho_mage'        => 10,
			  'psycho_necromancer' =>  5,
			  'psycho_escaper'     => 20,
			  'dream_eater_mad'    => 10,
			  'revive_ogre'        =>  5]],
	    'count' => [1, 1, 1]],
    'h' => ['fix' => ['human' => 2]],
    'i' => ['random' => [['jealousy'          => 27,
			  'divorce_jealousy'  => 15,
			  'flower_jealousy'   =>  5,
			  'priest_jealousy'   => 15,
			  'poison_jealousy'   => 10,
			  'miasma_jealousy'   =>  8,
			  'critical_jealousy' => 20],
			 ['cupid'           => 9,
			  'self_cupid'      => 5,
			  'moon_cupid'      => 3,
			  'altair_cupid'    => 3,
			  'sacrifice_cupid' => 2,
			  'mind_cupid'      => 3,
			  'sweet_cupid'     => 4,
			  'letter_cupid'    => 2,
			  'minstrel_cupid'  => 2,
			  'triangle_cupid'  => 4,
			  'nephila_cupid'   => 3,
			  'revive_cupid'    => 3,
			  'snow_cupid'      => 7,
			  'angel'           => 8,
			  'rose_angel'      => 8,
			  'lily_angel'      => 8,
			  'exchange_angel'  => 5,
			  'ark_angel'       => 5,
			  'sacrifice_angel' => 5,
			  'scarlet_angel'   => 5,
			  'cursed_angel'    => 6]],
	    'count' => [1, 2]],
    'j' => ['random' => [['duelist'          =>  8,
			  'valkyrja_duelist' =>  6,
			  'critical_duelist' =>  4,
			  'cowboy_duelist'   =>  6,
			  'triangle_duelist' =>  5,
			  'triphase_duelist' =>  5,
			  'doom_duelist'     =>  5,
			  'perverse_duelist' =>  5,
			  'sea_duelist'      =>  6,
			  'avenger'          =>  5,
			  'poison_avenger'   =>  2,
			  'cursed_avenger'   =>  2,
			  'critical_avenger' =>  2,
			  'trick_avenger'    =>  2,
			  'foughten_avenger' =>  2,
			  'revive_avenger'   =>  2,
			  'cute_avenger'     =>  3,
			  'patron'           =>  8,
			  'soul_patron'      =>  4,
			  'sacrifice_patron' =>  4,
			  'shepherd_patron'  =>  4,
			  'plumage_patron'   =>  4,
			  'critical_patron'  =>  6]],
	    'count' => [1]],
    'k' => ['random' => [['executor'             => 8,
			  'soul_mage'            => 4,
			  'soul_necromancer'     => 6,
			  'revive_medium'        => 6,
			  'high_priest'          => 6,
			  'poison_guard'         => 4,
			  'ghost_common'         => 4,
			  'strong_poison'        => 6,
			  'revive_cat'           => 6,
			  'alchemy_pharmacist'   => 6,
			  'soul_assassin'        => 4,
			  'clairvoyance_scanner' => 6,
			  'flower_jealousy'      => 6,
			  'barrier_brownie'      => 6,
			  'soul_wizard'          => 6,
			  'serve_doll_master'    => 8,
			  'divine_escaper'       => 8],
			 ['boss_wolf'      => 2,
			  'eye_wolf'       => 1,
			  'thorn_wolf'     => 1,
			  'sharp_wolf'     => 1,
			  'tongue_wolf'    => 1,
			  'possessed_wolf' => 1,
			  'sirius_wolf'    => 1,
			  'whisper_mad'    => 2],
			 ['cursed_fox'         =>  7,
			  'jammer_fox'         =>  5,
			  'sacrifice_depraver' =>  3,
			  'minstrel_cupid'     =>  9,
			  'sacrifice_angel'    =>  6,
			  'quiz'               =>  5,
			  'soul_vampire'       => 10,
			  'boss_chiroptera'    =>  9,
			  'ice_fairy'          =>  6,
			  'sacrifice_ogre'     =>  9,
			  'dowser_yaksa'       =>  6,
			  'critical_duelist'   =>  5,
			  'revive_avenger'     =>  3,
			  'sacrifice_patron'   =>  2,
			  'soul_tengu'         =>  5,
			  'soul_mania'         =>  5,
			  'sacrifice_mania'    =>  5]],
	    'count' => [1, 1, 1]],
    'l' => ['fix' => ['ghost_common' => 1,
		      'boss_wolf'    => 1,
		      'silver_wolf'  => 1,
		      'howl_fox'     => 1]],
    'm' => ['fix'    => ['trap_wolf' => 1, 'doom_fox' => 1],
	    'random' => [['step_assassin' => 3, 'sweep_assassin' => 7]],
	    'count'  => [2]],
    'n' => ['fix' => ['guard' => 1, 'trap_wolf' => 1, 'trap_mad' => 1]],
    'o' => ['fix' => ['voodoo_killer' => 1, 'cursed_yaksa' => 1, 'cursed_avenger' => 1],
	    'random' => [['wizard'            => 16,
			  'soul_wizard'       =>  4,
			  'esper_wizard'      =>  8,
			  'pierrot_wizard'    =>  6,
			  'awake_wizard'      =>  8,
			  'mimic_wizard'      => 10,
			  'plural_wizard'     =>  6,
			  'spark_wizard'      =>  6,
			  'spiritism_wizard'  => 10,
			  'philosophy_wizard' => 10,
			  'barrier_wizard'    =>  6,
			  'astray_wizard'     => 10]],
	    'count'  => [1]],
    'p' => ['fix' => ['step_wolf' => 1],
	    'random' => [['step_mage'     => 20,
			  'step_guard'    => 16,
			  'step_assassin' =>  7,
			  'step_scanner'  =>  7,
			  'step_mad'      => 18,
			  'step_fox'      => 12,
			  'step_vampire'  => 10,
			  'lute_mania'    =>  5,
			  'harp_mania'    =>  5]],
	    'count'  => [2]],
    'q' => ['random' => [['sex_mage' => 20,
			  'sex_wolf' => 2,
			  'sex_fox'  => 1],
			 ['incubus_escaper'      => 12,
			  'succubus_escaper'     => 12,
			  'homogeneous_wolf'     =>  6,
			  'heterologous_wolf'    =>  6,
			  'angel'                =>  6,
			  'rose_angel'           =>  6,
			  'lily_angel'           =>  6,
			  'incubus_vampire'      =>  5,
			  'succubus_vampire'     =>  5,
			  'homogeneous_vampire'  =>  5,
			  'heterologous_vampire' =>  5,
			  'incubus_ogre'         => 10,
			  'succubus_yaksa'       => 10,
			  'gender_fairy'         =>  6]],
	    'count'  => [1, 1]],
    'r' => ['random' => [['fairy'         => 1,
			  'spring_fairy'  => 1,
			  'summer_fairy'  => 1,
			  'autumn_fairy'  => 1,
			  'winter_fairy'  => 1,
			  'flower_fairy'  => 1,
			  'star_fairy'    => 1,
			  'sun_fairy'     => 1,
			  'moon_fairy'    => 1,
			  'grass_fairy'   => 1,
			  'light_fairy'   => 1,
			  'dark_fairy'    => 1,
			  'shadow_fairy'  => 1,
			  'greater_fairy' => 1,
			  'mirror_fairy'  => 1,
			  'sweet_fairy'   => 1,
			  'gender_fairy'  => 1,
			  'chill_fairy'   => 1,
			  'ice_fairy'     => 1],
			 ['dummy_guard'     => 1,
			  'dummy_poison'    => 1,
			  'dream_eater_mad' => 2]],
	    'count'  => [1, 1]],
    's' => ['fix'    => ['boss_wolf' => 1],
	    'random' => [['necromancer'       => 6,
			  'soul_necromancer'  => 1,
			  'dummy_necromancer' => 3],
			 ['white_fox'       => 3,
			  'black_fox'       => 5,
			  'cute_chiroptera' => 2]],
	    'count'  => [1,1]],
    't' => ['random' => [['tengu'         => 24,
			  'soul_tengu'    => 10,
			  'passion_tengu' => 12,
			  'meteor_tengu'  => 12,
			  'involve_tengu' => 12,
			  'priest_tengu'  => 14,
			  'eclipse_tengu' => 16]],
	    'count'  => [1]],
    'u' => ['fix'    => ['fanatic_mad' => 1],
	    'random' => [['depraver'           => 4,
			  'fire_depraver'      => 2,
			  'tailtip_depraver'   => 1,
			  'sacrifice_depraver' => 1,
			  'silver_depraver'    => 2]],
	    'count'  => [1]],
  ];

  //-- 出現率変動モード --//
  /*
    fix   : 個別指定
    zero  : 0 倍固定
    boost : 固定倍率
  */
  public static $boost_rate_fix_rate = 20;
  public static $boost_rate_list = [
    'a' => ['fix' => ['fetish_cat' => 20, 'rioter_mad' => 20]],
    'b' => ['zero' => ['elder',
		       'scripter',
		       'eccentricer',
		       'critical_mage',
		       'elder_guard',
		       'critical_common',
		       'critical_jealousy',
		       'brownie',
		       'harvest_brownie',
		       'maple_brownie',
		       'esper_wizard',
		       'philosophy_wizard',
		       'divine_escaper',
		       'ascetic_wolf',
		       'elder_wolf',
		       'possessed_mad',
		       'elder_fox',
		       'elder_chiroptera',
		       'critical_mad',
		       'critical_fox',
		       'altair_cupid',
		       'poison_ogre',
		       'critical_duelist',
		       'cowboy_duelist',
		       'critical_avenger',
		       'critical_patron',
		       'wirepuller_mania',
		       'mask_mania']],
    'c' => ['zero' => ['human',
		       'mage',
		       'necromancer',
		       'medium',
		       'priest',
		       'guard',
		       'common',
		       'poison',
		       'poison_cat',
		       'pharmacist',
		       'assassin',
		       'mind_scanner',
		       'jealousy',
		       'brownie',
		       'wizard',
		       'doll',
		       'escaper',
		       'wolf',
		       'mad',
		       'fox',
		       'child_fox',
		       'depraver',
		       'cupid',
		       'angel',
		       'quiz',
		       'vampire',
		       'chiroptera',
		       'fairy',
		       'ogre',
		       'yaksa',
		       'duelist',
		       'avenger',
		       'patron',
		       'tengu',
		       'mania',
		       'unknown_mania']],
    'd' => ['zero' => ['grave_guard',
		       'revive_medium',
		       'poison_cat',
		       'revive_cat',
		       'sacrifice_cat',
		       'doom_cat',
		       'missfire_cat',
		       'fetish_cat',
		       'eclipse_cat',
		       'revive_doll_master',
		       'possessed_mad',
		       'grave_mad',
		       'rioter_mad',
		       'possessed_fox',
		       'revive_fox',
		       'revive_mania']],
    'e' => ['zero' => ['possessed_wolf',
		       'possessed_mad',
		       'possessed_fox',
		       'exchange_angel']],
    'f' => ['zero' => ['depraver',
		       'fire_depraver',
		       'tailtip_depraver',
		       'sacrifice_depraver',
		       'silver_depraver',
		       'chiroptera',
		       'poison_chiroptera',
		       'follow_chiroptera',
		       'cursed_chiroptera',
		       'boss_chiroptera',
		       'elder_chiroptera',
		       'cute_chiroptera',
		       'doom_chiroptera',
		       'scarlet_chiroptera',
		       'dummy_chiroptera',
		       'fairy',
		       'spring_fairy',
		       'summer_fairy',
		       'autumn_fairy',
		       'winter_fairy',
		       'flower_fairy',
		       'star_fairy',
		       'sun_fairy',
		       'moon_fairy',
		       'grass_fairy',
		       'light_fairy',
		       'dark_fairy',
		       'shadow_fairy',
		       'greater_fairy',
		       'mirror_fairy',
		       'sweet_fairy',
		       'gender_fairy',
		       'chill_fairy',
		       'ice_fairy',
		       'ogre',
		       'orange_ogre',
		       'indigo_ogre',
		       'cow_ogre',
		       'horse_ogre',
		       'poison_ogre',
		       'west_ogre',
		       'east_ogre',
		       'north_ogre',
		       'south_ogre',
		       'incubus_ogre',
		       'wise_ogre',
		       'collector_ogre',
		       'power_ogre',
		       'revive_ogre',
		       'sacrifice_ogre',
		       'yaksa',
		       'betray_yaksa',
		       'cursed_yaksa',
		       'succubus_yaksa',
		       'hariti_yaksa',
		       'vajra_yaksa',
		       'power_yaksa',
		       'dowser_yaksa',
		       'duelist',
		       'valkyrja_duelist',
		       'critical_duelist',
		       'cowboy_duelist',
		       'triangle_duelist',
		       'triphase_duelist',
		       'doom_duelist',
		       'perverse_duelist',
		       'sea_duelist',
		       'avenger',
		       'poison_avenger',
		       'cursed_avenger',
		       'critical_avenger',
		       'trick_avenger',
		       'foughten_avenger',
		       'revive_avenger',
		       'cute_avenger',
		       'patron',
		       'soul_patron',
		       'sacrifice_patron',
		       'shepherd_patron',
		       'plumage_patron',
		       'critical_patron']],
    'g' => ['zero' => ['jealousy',
		       'divorce_jealousy',
		       'flower_jealousy',
		       'priest_jealousy',
		       'poison_jealousy',
		       'miasma_jealousy',
		       'critical_jealousy',
		       'cupid',
		       'self_cupid',
		       'moon_cupid',
		       'altair_cupid',
		       'sacrifice_cupid',
		       'mind_cupid',
		       'sweet_cupid',
		       'letter_cupid',
		       'minstrel_cupid',
		       'triangle_cupid',
		       'nephila_cupid',
		       'revive_cupid',
		       'snow_cupid',
		       'angel',
		       'rose_angel',
		       'lily_angel',
		       'exchange_angel',
		       'ark_angel',
		       'sacrifice_angel',
		       'scarlet_angel',
		       'cursed_angel']],
    'h' => ['zero' => ['poison_guard',
		       'poison',
		       'strong_poison',
		       'incubate_poison',
		       'guide_poison',
		       'snipe_poison',
		       'chain_poison',
		       'dummy_poison',
		       'poison_cat',
		       'pharmacist',
		       'cure_pharmacist',
		       'revive_pharmacist',
		       'alchemy_pharmacist',
		       'centaurus_pharmacist',
		       'poison_jealousy',
		       'poison_doll',
		       'poison_wolf',
		       'resist_wolf',
		       'poison_fox',
		       'poison_vampire',
		       'poison_chiroptera',
		       'horse_ogre',
		       'poison_ogre',
		       'poison_avenger',
		       'plumage_patron']],
    'i' => ['zero' => ['tough',
		       'medium',
		       'bacchus_medium',
		       'seal_medium',
		       'revive_medium',
		       'eclipse_medium',
		       'grave_guard',
		       'ghost_common',
		       'doom_assassin',
		       'step_assassin',
		       'doom_cat',
		       'cure_pharmacist',
		       'revive_pharmacist',
		       'jealousy',
		       'miasma_jealousy',
		       'brownie',
		       'thunder_brownie',
		       'harvest_brownie',
		       'maple_brownie',
		       'cursed_brownie',
		       'soul_wizard',
		       'pierrot_wizard',
		       'esper_wizard',
		       'philosophy_wizard',
		       'astray_wizard',
		       'doom_doll',
		       'doom_escaper',
		       'purple_wolf',
		       'snow_wolf',
		       'miasma_wolf',
		       'homogeneous_wolf',
		       'heterologous_wolf',
		       'fortitude_wolf',
		       'thorn_wolf',
		       'doom_wolf',
		       'seiren_mad',
		       'grave_mad',
		       'snow_trap_mad',
		       'agitate_mad',
		       'miasma_mad',
		       'follow_mad',
		       'purple_fox',
		       'snow_fox',
		       'fortitude_fox',
		       'doom_fox',
		       'miasma_fox',
		       'moon_cupid',
		       'revive_cupid',
		       'snow_cupid',
		       'cursed_angel',
		       'doom_vampire',
		       'follow_chiroptera',
		       'doom_chiroptera',
		       'chill_fairy',
		       'ice_fairy',
		       'poison_ogre',
		       'cowboy_duelist',
		       'triphase_duelist',
		       'doom_duelist',
		       'perverse_duelist',
		       'sea_duelist',
		       'cursed_avenger',
		       'tengu',
		       'soul_tengu',
		       'passion_tengu',
		       'meteor_tengu',
		       'involve_tengu',
		       'priest_tengu',
		       'eclipse_tengu']],
    'j' => ['zero' => ['voodoo_killer',
		       'anti_voodoo',
		       'cursed_brownie',
		       'astray_wizard',
		       'cursed_wolf',
		       'voodoo_mad',
		       'voodoo_fox',
		       'cursed_fox',
		       'cursed_angel',
		       'cursed_chiroptera',
		       'cursed_yaksa',
		       'cursed_avenger']],
    'k' => ['zero' => ['suspect',
		       'dummy_mage',
		       'dummy_necromancer',
		       'eclipse_medium',
		       'dummy_priest',
		       'dummy_guard',
		       'dummy_common',
		       'dummy_poison',
		       'eclipse_cat',
		       'centaurus_pharmacist',
		       'eclipse_assassin',
		       'dummy_scanner',
		       'critical_jealousy',
		       'maple_brownie',
		       'astray_wizard',
		       'silver_doll',
		       'stargazer_escaper',
		       'emperor_wolf',
		       'dream_eater_mad',
		       'immolate_mad',
		       'immolate_fox',
		       'critical_fox',
		       'silver_depraver',
		       'snow_cupid',
		       'cursed_angel',
		       'quiz',
		       'scarlet_vampire',
		       'dummy_chiroptera',
		       'mirror_fairy',
		       'incubus_ogre',
		       'succubus_yaksa',
		       'sea_duelist',
		       'cute_avenger',
		       'critical_patron',
		       'eclipse_tengu',
		       'dummy_mania']],
    'l' => ['zero' => ['doll',
		       'friend_doll',
		       'phantom_doll',
		       'poison_doll',
		       'doom_doll',
		       'revive_doll',
		       'scarlet_doll',
		       'silver_doll',
		       'escaper',
		       'psycho_escaper',
		       'incubus_escaper',
		       'succubus_escaper',
		       'doom_escaper',
		       'agent_escaper',
		       'divine_escaper',
		       'stargazer_escaper',
		       'emperor_wolf',
		       'spy_mad',
		       'immolate_mad',
		       'immolate_fox',
		       'critical_fox']],
    'm' => ['zero' => ['puppet_mage',
		       'scarlet_doll',
		       'silver_doll',
		       'toy_doll_master',
		       'blue_wolf',
		       'scarlet_wolf',
		       'silver_wolf',
		       'blue_fox',
		       'scarlet_fox',
		       'silver_fox',
		       'silver_depraver',
		       'scarlet_angel',
		       'scarlet_vampire',
		       'scarlet_chiroptera',
		       'scarlet_mania']],
    'n' => ['zero' => ['mania',
		       'trick_mania',
		       'basic_mania',
		       'scarlet_mania',
		       'soul_mania',
		       'dummy_mania',
		       'unknown_mania',
		       'wirepuller_mania',
		       'fire_mania',
		       'sacrifice_mania',
		       'resurrect_mania',
		       'revive_mania',
		       'lute_mania',
		       'harp_mania',
		       'mask_mania']]
  ];

  //-- 博物館モード(追加型) --//
  /* $topping_list とルールは同じ */
  public static $museum_topping_list = [
    //TypeA: 管理者設定
    'a1' => [],
    //TypeB: Ver. 1.4.0
    'b1' => ['fix' => ['quiz' => 1]],
    'b2' => ['pick' => [['list' => ['soul_mage', 'medium', 'poison_guard'],
			 'count' => 1],
			['list' => ['boss_wolf', 'fanatic_mad', 'child_fox'],
			 'count' => 1]]],
    'b3' => ['fix' => ['suspect' => 1]],
    'b4' => ['fix' => ['mania' => 1]],
    'b5' => ['fix' => ['poison_wolf' => 1, 'pharmacist' => 1]],
    'b6' => ['fix' => ['unconscious' => 1, 'tongue_wolf' => 1]],
    'b7' => ['fix' => ['dummy_mage' => 1, 'reporter' => 1, 'cute_wolf' => 1]],
    'b8' => ['pick' => [['list' => [
			   'dummy_necromancer', 'dummy_guard', 'dummy_common', 'dummy_poison',
			   'soul_necromancer', 'strong_poison', 'incubate_poison'],
			 'count' => 1],
			['list' => ['cursed_wolf', 'resist_wolf', 'whisper_mad'],
			 'count' => 1],
			['list' => ['white_fox', 'poison_fox', 'cursed_fox'],
			 'count'  => 1]]],
    'b9' => ['pick' => [['list' => ['psycho_mage', 'poison_cat', 'assassin', 'trap_mad'],
			 'count' => 3]]],
    'b10' => ['fix' => ['jammer_mad' => 1, 'sex_mage' => 1]],
    'b11' => ['pick' => [['list' => ['anti_voodoo', 'voodoo_killer', 'yama_necromancer'],
			  'count' => 1],
			 ['list' => ['voodoo_mad', 'voodoo_fox', 'silver_fox'],
			  'count' => 1]]],
    'b12' => ['pick' => [['list' => [
                            'mind_scanner', 'silver_wolf', 'dream_eater_mad', 'corpse_courier_mad',
			    'self_cupid'],
			  'count' => 2],
			 ['list' => ['chiroptera', 'poison_chiroptera', 'cursed_chiroptera'],
			  'count' => 1]]],
    'b13' => ['fix' => ['jealousy' => 1]],
    'b14' => ['fix' => ['unknown_mania' => 1, 'mind_cupid' => 1]],
    'b15' => ['pick' => [['list' => ['priest', 'dummy_chiroptera'],
			  'count' => 1],
			 ['list' => ['wise_wolf', 'possessed_wolf', 'scarlet_wolf'],
			  'count' => 1],
			 ['list' => ['black_fox', 'cute_fox', 'scarlet_fox'],
			  'count' => 1]]],
    'b16' => ['pick' => [['list' => ['crisis_priest', 'revive_priest', 'evoke_scanner'],
			  'count' => 1],
			 ['list' => ['revive_cat', 'revive_fox'],
			  'count' => 1]]],
    'b17' => ['pick' => [['list' => [
			    'elder', 'elder_wolf', 'elder_fox', 'elder_chiroptera', 'fend_guard'],
			  'count' => 3]]],
    'b18' => ['pick' => [['list' => [
			    'trap_common', 'ghost_common', 'chain_poison', 'poison_jealousy'],
			  'count' => 1],
			 ['list' => [
			    'fairy', 'spring_fairy', 'summer_fairy', 'autumn_fairy', 'winter_fairy'],
			  'count' => 1]]],
    'b19' => ['pick' => [['list' => ['saint', 'agitate_mad'],
			  'count' => 1],
			 ['list' => ['light_fairy', 'dark_fairy', 'mirror_fairy'],
			  'count' => 1]]],
    'b20' => ['pick' => [['list' => ['gold_wolf', 'blue_wolf', 'emerald_wolf', 'sex_wolf'],
			  'count' => 1],
			 ['list' => ['gold_fox', 'blue_fox', 'emerald_fox', 'sex_fox'],
			  'count' => 1],
			 ['list' => [
			    'triangle_cupid', 'angel', 'rose_angel', 'lily_angel', 'ark_angel'],
			  'count' => 1]]],
    'b21' => ['pick' => [['list' => [
			    'executor', 'sacrifice_cat', 'cure_pharmacist', 'reverse_assassin',
			    'eclipse_assassin'],
			  'count' => 1],
			 ['list' => ['sirius_wolf', 'possessed_mad', 'miasma_mad', 'possessed_fox'],
			  'count' => 1],
			 ['list' => ['boss_chiroptera', 'trick_mania'],
			  'count' => 1]]],
    'b22' => ['pick' => [['list' => [
			    'bishop_priest', 'detective_common', 'doom_assassin',
			    'doll', 'friend_doll', 'poison_doll', 'doll_master'],
			  'count' => 2]]],
    'b23' => ['pick' => [['list' => [
			    'guide_poison', 'whisper_scanner', 'howl_scanner', 'telepath_scanner',
			    'escaper'],
			  'count' => 1],
			 ['list' => ['phantom_wolf', 'phantom_fox', 'moon_cupid', 'exchange_angel'],
			  'count' => 1],
			 ['list' => ['soul_mania', 'dummy_mania'],
			  'count' => 1]]],
    'b24' => ['pick' => [['list' => [
			    'stargazer_mage', 'border_priest', 'hungry_wolf', 'flower_fairy'],
			  'count' => 2]]],
    'b25' => ['pick' => [['list' => [
			    'seal_medium', 'revive_medium', 'hunter_guard', 'soul_assassin',
			    'doom_doll'],
			  'count' => 1],
			 ['list' => ['stargazer_fox', 'jammer_fox', 'miasma_fox'],
			  'count' => 1],
			 ['list' => ['grass_fairy', 'sun_fairy', 'moon_fairy', 'star_fairy'],
			  'count' => 1]]],
    'b26' => ['fix' => ['blind_guard' => 1, 'vampire' => 1]],
    'b27' => ['pick' => [['list' => ['dowser_priest', 'dummy_priest', 'revive_pharmacist',
				     'brownie'],
			  'count' => 1],
			 ['list' => ['doom_wolf', 'therian_mad', 'doom_fox'],
			  'count' => 1]]],
    'b28' => ['fix' => ['history_brownie' => 1, 'snow_trap_mad' => 1, 'ice_fairy' => 1]],
    'b29' => ['pick' => [['list' => [
			    'priest_jealousy', 'eclipse_cat', 'enchant_mad', 'howl_fox',
			    'sacrifice_vampire'],
			  'count' => 2]]],
    'b30' => ['pick' => [['list' => ['presage_scanner', 'sacrifice_angel', 'sacrifice_mania'],
			  'count' => 1],
			 ['list' => ['incubus_vampire', 'succubus_vampire'],
			  'count' => 1],
			 ['list' => ['ogre', 'orange_ogre', 'indigo_ogre'],
			  'count' => 1]]],
    'b31' => ['pick' => [['list' => ['divorce_jealousy', 'amaze_mad'],
			  'count' => 1],
			 ['list' => ['poison_ogre', 'east_ogre', 'west_ogre', 'north_ogre',
				     'south_ogre', 'wise_ogre', 'yaksa', 'incubus_ogre',
				     'succubus_yaksa'],
			  'count' => 1],
			 ['list' => ['doom_vampire', 'soul_vampire'],
			  'count' => 1]]],
    'b32' => ['pick' => [['list' => ['attempt_necromancer', 'revive_brownie', 'cursed_brownie',
				     'phantom_doll', 'revive_doll'],
			  'count' => 1],
			 ['list' => ['sacrifice_ogre', 'shadow_fairy'],
			  'count' => 1]]],
    'b33' => ['pick' => [['list' => [
			    'bacchus_medium', 'high_priest', 'scarlet_doll', 'silver_doll'],
			  'count' => 1],
			 ['list' => ['scarlet_chiroptera', 'power_ogre', 'dowser_yaksa'],
			  'count' => 1]]],
    'b34' => ['pick' => [['list' => [
			    'scripter', 'reflect_guard', 'alchemy_pharmacist',
			    'clairvoyance_scanner', 'incubus_escaper'],
			  'count' => 1],
			 ['list' => ['sweet_cupid', 'revive_ogre'],
			  'count' => 1]]],
    //TypeC: Ver. 1.5.0
    'c1' => ['fix' => ['wizard' => 1, 'soul_wizard' => 1]],
    'c2' => ['fix' => ['embalm_necromancer' => 1, 'emissary_necromancer' => 1]],
    'c3' => ['fix' => ['weather_priest' => 1, 'awake_wizard' => 1]],
    'c4' => ['pick' => [['list' => [
			   'sun_brownie', 'critical_mad', 'follow_mad', 'wirepuller_mania'],
			 'count' => 2]]],
    'c5' => ['pick' => [['list' => [
			   'psycho_necromancer', 'spiritism_wizard', 'barrier_wizard', 'revive_wolf'],
			 'count' => 2]]],
    'c6' => ['pick' => [['list' => [
			   'gatekeeper_guard', 'psycho_escaper', 'cute_chiroptera',
			   'betray_yaksa', 'cursed_yaksa'],
			 'count' => 3]]],
    'c7' => ['fix' => ['pierrot_wizard' => 1, 'astray_wizard' => 1],
	     'pick' => [['list' => ['trap_wolf', 'trap_fox'],
			 'count' => 1]]],
    'c8' => ['fix' => ['immolate_mad' => 1, 'immolate_fox' => 1],
	     'pick' => [['list' => ['incubus_escaper', 'doom_escaper'],
			 'count' => 1]]],
    'c9' => ['fix' => ['greater_fairy' => 1],
	     'pick' => [['list' => ['minstrel_cupid', 'scarlet_angel'],
			  'count' => 1],
			 ['list' => ['duelist', 'valkyrja_duelist', 'triangle_duelist'],
			  'count' => 1]]],
    'c10' => ['fix' => ['sacrifice_common' => 1, 'centaurus_pharmacist' => 1]],
    'c11' => ['pick' => [['list' => ['doom_duelist', 'avenger', 'patron'],
			 'count' => 2]]],
    'c12' => ['pick' => [['list' => ['basic_mania', 'divine_escaper'],
			  'count' => 1],
			 ['list' => ['critical_duelist', 'sacrifice_patron', 'shepherd_patron'],
			  'count' => 1],
			 ['list' => ['poison_avenger', 'cursed_avenger', 'critical_avenger',
				     'revive_avenger'],
			  'count' => 1]]],
    'c13' => ['pick' => [['list' => ['widow_priest', 'scarlet_vampire', 'sweet_fairy'],
			  'count' => 2],
			 ['list' => ['soul_patron', 'cute_avenger', 'cowboy_duelist',
				     'critical_patron'],
			  'count' => 1]]],
    'c14' => ['pick' => [['list' => ['fire_wolf', 'mist_wolf'],
			  'count' => 1],
			 ['list' => ['spell_fox', 'mist_fox'],
			  'count' => 1]]],
    'c15' => ['fix' => ['puppet_mage' => 1, 'elder_guard' => 1],
	      'pick' => [['list' => ['snow_cupid', 'cursed_angel'],
			  'count' => 1]]],
    'c16' => ['pick' => [['list' => ['cute_mage', 'eclipse_medium', 'leader_common', 'snipe_poison'],
			  'count' => 1],
			 ['list' => ['miasma_jealousy', 'critical_jealousy'],
			  'count' => 1],
			 ['list' => ['wise_ogre', 'power_yaksa'],
			  'count' => 1]]],
    'c17' => ['fix' => ['quiet_wolf' => 1, 'hariti_yaksa' => 1],
	      'pick' => [['list' => ['critical_common', 'hermit_common', 'philosophy_wizard'],
			  'count' => 1]]],
    'c18' => ['fix' => ['select_assassin' => 1, 'missfire_cat' => 1]],
    'c19' => ['fix' => ['fire_mania' => 1, 'revive_mania' => 1]],
    'c20' => ['fix' => ['echo_brownie' => 1, 'resurrect_mania' => 1],
	      'pick' => [['list' => ['sacrifice_fox', 'revive_mad', 'revive_cupid'],
			  'count' => 1]]],
    'c21' => ['fix' => ['spell_common' => 1, 'holy_priest' => 1, 'sharp_wolf' => 1]],
    'c22' => ['fix' => ['thunder_brownie' => 1, 'mimic_wizard' => 1]],
    'c23' => ['fix' => ['dummy_scanner' => 1],
	     'pick' => [['list' => ['harvest_brownie', 'maple_brownie'],
			 'count' => 1],
			['list' => ['monk_fox', 'critical_fox'],
			 'count' => 1]]],
    'c24' => ['fix' => ['emperor_wolf' => 1]],
    //TypeD: Ver. 2.1.0
    'd1' => ['fix' => ['swindle_mad' => 1]],
    'd2' => ['fix' => ['eccentricer' => 1]],
    'd3' => ['fix' => ['disguise_wolf' => 1]],
    'd4' => ['fix' => ['decieve_wolf' => 1]],
    'd5' => ['pick' => [['list' => ['purple_wolf', 'snow_wolf'],
			 'count' => 1],
			['list' => ['purple_fox', 'snow_fox'],
			 'count' => 1]]],
    'd6' => ['pick' => [['list' => ['sweep_assassin', 'professional_assassin', 'ascetic_assassin'],
			 'count' => 1],
			['list' => ['ascetic_wolf', 'vindictive_fox', 'vajra_yaksa'],
			 'count' => 2]]],
    'd7' => ['pick' => [['list' => ['poison_vampire', 'passion_vampire'],
			 'count' => 1]]],
    //TypeE: Ver. 2.2.0
    'e1' => ['pick' => [['list' => ['step_mage', 'step_guard'],
			  'count' => 1],
			 ['list' => ['step_wolf', 'step_mad', 'step_fox'],
			  'count' => 1]]],
    'e2' => ['fix' => ['step_vampire' => 1]],
    'e3' => ['fix' => ['cow_ogre' => 1, 'horse_ogre' => 1]],
    'e4' => ['fix' => ['fire_mad' => 1, 'sea_duelist' => 1]],
    'e5' => ['fix' => ['plumage_patron' => 1, 'scarlet_mania' => 1]],
    'e6' => ['fix' => ['tough' => 1]],
    //TypeF: Ver. 2.3.0
    'f1' => ['fix' => ['altair_cupid' => 1]],
    'f2' => ['fix' => ['nephila_cupid' => 1, 'doom_chiroptera' => 1]],
    'f3' => ['pick' => [['list' => ['depraver', 'sacrifice_depraver', 'silver_depraver'],
			 'count' => 2]]],
    'f4' => ['fix' => ['honey_wolf' => 1],
	     'pick' => [['list' => ['lute_mania', 'harp_mania'],
			 'count' => 1]]],
    'f5' => ['fix' => ['prince' => 1, 'perverse_duelist' => 1]],
    'f6' => ['pick' => [['list' => ['wanderer_guard', 'step_assassin', 'step_scanner'],
			 'count' => 2]]],
    //TypeG: Ver. 3.0.0
    'g1' => ['pick' => [['list' => ['tengu', 'soul_tengu', 'eclipse_tengu'],
			 'count' => 2]]],
    'g2' => ['fix' => ['tiger_wolf' => 1, 'tiger_fox' => 1, 'fire_depraver' => 1]],
    'g3' => ['pick' => [['list' => ['toy_doll_master', 'revive_doll_master', 'serve_doll_master'],
			 'count' => 1]]],
    'g4' => ['fix' => ['critical_mage' => 1, 'barrier_brownie' => 1, 'passion_tengu' => 1]],
    'g5' => ['fix' => ['eye_scanner' => 1, 'eye_wolf' => 1, 'letter_cupid' => 1]],
    'g6' => ['fix' => ['meteor_tengu' => 1, 'priest_tengu' => 1]],
    //TypeH: Ver. 3.1.0
    'h1' => ['fix' => ['mask_mania' => 1]],
    'h2' => ['pick' => [['list' => ['stargazer_escaper', 'involve_tengu', 'grave_guard', 'grave_mad'],
			 'count' => 2]]],
    'h3' => ['fix' => ['doom_cat' => 1, 'foughten_avenger' => 1]],
    'h4' => ['fix' => ['agent_escaper' => 1, 'follow_vampire' => 1]],
    'h5' => ['pick' => [['list' => ['seiren_mad', 'fortitude_wolf', 'fortitude_fox'],
			 'count' => 2]]],
    'h6' => ['fix' => ['thorn_wolf' => 1, 'collector_ogre' => 1]],
    'h7' => ['fix' => ['spy_mad' => 1]],
    'h8' => ['fix' => ['esper_wizard' => 1, 'chill_fairy' => 1],
	     'pick' => [['list' => ['triphase_duelist', 'trick_avenger'],
			 'count' => 1]]],
    //TypeI: Ver. 4.1.0
    'i1' => ['fix' => ['gender_fairy' => 1],
	     'pick' => [['list' => ['homogeneous_vampire', 'heterologous_vampire'],
			 'count' => 1]]],
    //TypeJ: Ver. 5.1.0
    'j1' => ['fix' => ['sacrifice_cupid' => 1, 'flower_jealousy' => 1]],
    'j2' => ['fix' => ['spell_wolf' => 1, 'miasma_wolf' => 1]],
    'j3' => ['fix' => ['plural_wizard' => 1, 'plural_mad' => 1],
	     'pick' => [['list' => ['sweet_wolf', 'sweet_fox'],
			 'count' => 1]]],
    'j4' => ['fix' => ['finder_guard' => 1],
	     'pick' => [['list' => ['homogeneous_wolf', 'heterologous_wolf'],
			 'count' => 1]]],
    'j5' => ['fix' => ['spark_wizard' => 1, 'tailtip_depraver' => 1]],
    'j6' => ['fix' => ['follow_chiroptera' => 1]],
    'j7' => ['fix' => ['fetish_cat' => 1, 'rioter_mad' => 1]],
  ];

  //-- 博物館モード(倍率型) --//
  /* $boost_rate_list とルールは同じ */
  public static $museum_boost_fix_rate = 10;
  public static $museum_boost_list = [
    //TypeA: 管理者設定
    'a1' => [],
    //TypeB: Ver. 1.4.0
    'b1'  => ['boost' => ['quiz']],
    'b2'  => ['boost' => ['soul_mage', 'medium', 'poison_guard', 'boss_wolf', 'fanatic_mad', 'child_fox']],
    'b3'  => ['boost' => ['suspect']],
    'b4'  => ['boost' => ['mania']],
    'b5'  => ['boost' => ['pharmacist', 'poison_wolf']],
    'b6'  => ['boost' => ['unconscious', 'tongue_wolf']],
    'b7'  => ['boost' => ['dummy_mage', 'reporter', 'cute_wolf']],
    'b8'  => ['boost' => ['dummy_necromancer', 'dummy_guard', 'dummy_common', 'dummy_poison',
			  'soul_necromancer', 'strong_poison', 'incubate_poison',
			  'cursed_wolf', 'resist_wolf', 'whisper_mad',
			  'white_fox', 'poison_fox', 'cursed_fox']],
    'b9'  => ['boost' => ['psycho_mage', 'poison_cat', 'assassin', 'trap_mad']],
    'b10' => ['boost' => ['sex_mage', 'jammer_mad']],
    'b11' => ['boost' => ['anti_voodoo', 'voodoo_killer', 'yama_necromancer',
			  'voodoo_mad', 'voodoo_fox', 'silver_fox']],
    'b12' => ['boost' => ['mind_scanner', 'silver_wolf', 'dream_eater_mad', 'corpse_courier_mad',
			  'self_cupid', 'chiroptera', 'poison_chiroptera', 'cursed_chiroptera']],
    'b13' => ['boost' => ['jealousy']],
    'b14' => ['boost' => ['mind_cupid', 'unknown_mania']],
    'b15' => ['boost' => ['priest', 'dummy_chiroptera',
			  'wise_wolf', 'possessed_wolf', 'scarlet_wolf',
			  'black_fox', 'cute_fox', 'scarlet_fox']],
    'b16' => ['boost' => ['crisis_priest', 'revive_priest', 'evoke_scanner',
			  'revive_cat', 'revive_fox']],
    'b17' => ['boost' => ['elder', 'elder_wolf', 'elder_fox', 'elder_chiroptera', 'fend_guard']],
    'b18' => ['boost' => ['trap_common', 'ghost_common', 'chain_poison', 'poison_jealousy',
			  'fairy', 'spring_fairy', 'summer_fairy', 'autumn_fairy', 'winter_fairy']],
    'b19' => ['boost' => ['saint', 'agitate_mad', 'light_fairy', 'dark_fairy', 'mirror_fairy']],
    'b20' => ['boost' => ['gold_wolf', 'blue_wolf', 'emerald_wolf', 'sex_wolf',
			  'gold_fox', 'blue_fox', 'emerald_fox', 'sex_fox',
			  'triangle_cupid', 'angel', 'rose_angel', 'lily_angel', 'ark_angel']],
    'b21' => ['boost' => ['executor', 'sacrifice_cat', 'cure_pharmacist', 'reverse_assassin',
			  'eclipse_assassin', 'sirius_wolf', 'possessed_mad', 'miasma_mad',
			  'possessed_fox', 'boss_chiroptera', 'trick_mania']],
    'b22' => ['boost' => ['bishop_priest', 'detective_common', 'doom_assassin',
			  'doll', 'friend_doll', 'poison_doll', 'doll_master']],
    'b23' => ['boost' => ['guide_poison', 'whisper_scanner', 'howl_scanner', 'telepath_scanner',
			  'escaper', 'phantom_wolf', 'phantom_fox', 'moon_cupid', 'exchange_angel',
			  'soul_mania', 'dummy_mania']],
    'b24' => ['boost' => ['stargazer_mage', 'border_priest', 'hungry_wolf', 'flower_fairy']],
    'b25' => ['boost' => ['seal_medium', 'revive_medium', 'hunter_guard', 'soul_assassin',
			  'doom_doll', 'stargazer_fox', 'jammer_fox', 'miasma_fox',
			  'grass_fairy', 'sun_fairy', 'moon_fairy', 'star_fairy']],
    'b26' => ['boost' => ['blind_guard' , 'vampire']],
    'b27' => ['boost' => ['dowser_priest', 'dummy_priest', 'revive_pharmacist',
			  'brownie', 'doom_wolf', 'therian_mad', 'doom_fox']],
    'b28' => ['boost' => ['history_brownie', 'snow_trap_mad', 'ice_fairy']],
    'b29' => ['boost' => ['priest_jealousy', 'eclipse_cat', 'enchant_mad', 'howl_fox',
			  'sacrifice_vampire']],
    'b30' => ['boost' => ['presage_scanner', 'sacrifice_angel', 'sacrifice_mania',
			  'incubus_vampire', 'succubus_vampire',
			  'ogre', 'orange_ogre', 'indigo_ogre']],
    'b31' => ['boost' => ['divorce_jealousy', 'amaze_mad',
			  'poison_ogre', 'east_ogre', 'west_ogre', 'north_ogre',
			  'south_ogre', 'wise_ogre', 'yaksa', 'incubus_ogre', 'succubus_yaksa',
			  'doom_vampire', 'soul_vampire']],
    'b32' => ['boost' => ['attempt_necromancer', 'revive_brownie', 'cursed_brownie',
			  'phantom_doll', 'revive_doll', 'sacrifice_ogre', 'shadow_fairy']],
    'b33' => ['boost' => ['bacchus_medium', 'high_priest', 'scarlet_doll', 'silver_doll',
			  'scarlet_chiroptera', 'power_ogre', 'dowser_yaksa']],
    'b34' => ['boost' => ['scripter', 'reflect_guard', 'alchemy_pharmacist',
			  'clairvoyance_scanner', 'incubus_escaper', 'sweet_cupid', 'revive_ogre']],
    //TypeC: Ver. 1.5.0
    'c1'  => ['boost' => ['wizard', 'soul_wizard']],
    'c2'  => ['boost' => ['embalm_necromancer', 'emissary_necromancer']],
    'c3'  => ['boost' => ['weather_priest', 'awake_wizard']],
    'c4'  => ['boost' => ['sun_brownie', 'critical_mad', 'follow_mad', 'wirepuller_mania']],
    'c5'  => ['boost' => ['psycho_necromancer', 'spiritism_wizard', 'barrier_wizard',
			  'revive_wolf']],
    'c6'  => ['boost' => ['gatekeeper_guard', 'psycho_escaper', 'cute_chiroptera',
			  'betray_yaksa', 'cursed_yaksa']],
    'c7'  => ['boost' => ['pierrot_wizard', 'astray_wizard', 'trap_wolf', 'trap_fox']],
    'c8'  => ['boost' => ['immolate_mad', 'immolate_fox', 'incubus_escaper', 'doom_escaper']],
    'c9'  => ['boost' => ['greater_fairy', 'minstrel_cupid', 'scarlet_angel',
			  'duelist', 'valkyrja_duelist', 'triangle_duelist']],
    'c10' => ['boost' => ['sacrifice_common', 'centaurus_pharmacist']],
    'c11' => ['boost' => ['doom_duelist', 'avenger', 'patron']],
    'c12' => ['boost' => ['basic_mania', 'divine_escaper', 'critical_duelist', 'sacrifice_patron',
			  'shepherd_patron', 'poison_avenger', 'cursed_avenger', 'critical_avenger',
			  'revive_avenger']],
    'c13' => ['boost' => ['widow_priest', 'scarlet_vampire', 'sweet_fairy',
			  'soul_patron', 'cute_avenger', 'cowboy_duelist', 'critical_patron']],
    'c14' => ['boost' => ['fire_wolf', 'mist_wolf', 'spell_fox', 'mist_fox']],
    'c15' => ['boost' => ['puppet_mage', 'elder_guard', 'snow_cupid', 'cursed_angel']],
    'c16' => ['boost' => ['cute_mage', 'eclipse_medium', 'leader_common', 'snipe_poison',
			  'miasma_jealousy', 'critical_jealousy', 'wise_ogre', 'power_yaksa']],
    'c17' => ['boost' => ['quiet_wolf', 'hariti_yaksa',
			  'critical_common', 'hermit_common', 'philosophy_wizard']],
    'c18' => ['boost' => ['select_assassin', 'missfire_cat']],
    'c19' => ['boost' => ['fire_mania', 'revive_mania']],
    'c20' => ['boost' => ['echo_brownie', 'resurrect_mania',
			  'sacrifice_fox', 'revive_mad', 'revive_cupid']],
    'c21' => ['boost' => ['spell_common', 'holy_priest', 'sharp_wolf']],
    'c22' => ['boost' => ['thunder_brownie', 'mimic_wizard']],
    'c23' => ['boost' => ['dummy_scanner', 'harvest_brownie', 'maple_brownie',
			  'monk_fox', 'critical_fox']],
    'c24' => ['boost' => ['emperor_wolf']],
    //TypeD: Ver. 2.1.0
    'd1' => ['boost' => ['swindle_mad']],
    'd2' => ['boost' => ['eccentricer']],
    'd3' => ['boost' => ['disguise_wolf']],
    'd4' => ['boost' => ['decieve_wolf']],
    'd5' => ['boost' => ['purple_wolf', 'snow_wolf', 'purple_fox', 'snow_fox']],
    'd6' => ['boost' => ['sweep_assassin', 'professional_assassin', 'ascetic_assassin',
			 'ascetic_wolf', 'vindictive_fox', 'vajra_yaksa']],
    'd7' => ['boost' => ['poison_vampire', 'passion_vampire']],
    //TypeE: Ver. 2.2.0
    'e1' => ['boost' => ['step_mage', 'step_guard', 'step_wolf', 'step_mad', 'step_fox']],
    'e2' => ['boost' => ['step_vampire']],
    'e3' => ['boost' => ['cow_ogre', 'horse_ogre']],
    'e4' => ['boost' => ['fire_mad', 'sea_duelist']],
    'e5' => ['boost' => ['plumage_patron', 'scarlet_mania']],
    'e6' => ['boost' => ['tough']],
    //TypeF: Ver. 2.3.0
    'f1' => ['boost' => ['altair_cupid']],
    'f2' => ['boost' => ['nephila_cupid', 'doom_chiroptera']],
    'f3' => ['boost' => ['depraver', 'sacrifice_depraver', 'silver_depraver']],
    'f4' => ['boost' => ['honey_wolf', 'lute_mania', 'harp_mania']],
    'f5' => ['boost' => ['prince', 'perverse_duelist']],
    'f6' => ['boost' => ['wanderer_guard', 'step_assassin', 'step_scanner']],
    //TypeG: Ver. 3.0.0
    'g1' => ['boost' => ['tengu', 'soul_tengu', 'eclipse_tengu']],
    'g2' => ['boost' => ['tiger_wolf', 'tiger_fox', 'fire_depraver']],
    'g3' => ['boost' => ['toy_doll_master', 'revive_doll_master', 'serve_doll_master']],
    'g4' => ['boost' => ['critical_mage', 'barrier_brownie', 'passion_tengu']],
    'g5' => ['boost' => ['eye_scanner', 'eye_wolf', 'letter_cupid']],
    'g6' => ['boost' => ['meteor_tengu', 'priest_tengu']],
    //TypeH: Ver. 3.1.0
    'h1' => ['boost' => ['mask_mania']],
    'h2' => ['boost' => ['stargazer_escaper', 'involve_tengu', 'grave_guard', 'grave_mad']],
    'h3' => ['boost' => ['doom_cat', 'foughten_avenger']],
    'h4' => ['boost' => ['agent_escaper', 'follow_vampire']],
    'h5' => ['boost' => ['seiren_mad', 'fortitude_wolf', 'fortitude_fox']],
    'h6' => ['boost' => ['thorn_wolf', 'collector_ogre']],
    'h7' => ['boost' => ['spy_mad']],
    'h8' => ['boost' => ['esper_wizard', 'chill_fairy', 'triphase_duelist', 'trick_avenger']],
    //TypeI: Ver. 4.1.0
    'i1' => ['boost' => ['homogeneous_vampire', 'heterologous_vampire', 'gender_fairy']],
    //TypeJ: Ver. 5.1.0
    'j1' => ['boost' => ['sacrifice_cupid', 'flower_jealousy']],
    'j2' => ['boost' => ['spell_wolf', 'miasma_wolf']],
    'j3' => ['boost' => ['plural_wizard' , 'plural_mad', 'sweet_wolf', 'sweet_fox']],
    'j4' => ['boost' => ['finder_guard', 'homogeneous_wolf', 'heterologous_wolf']],
    'j5' => ['boost' => ['spark_wizard', 'tailtip_depraver']],
    'j6' => ['boost' => ['follow_chiroptera']],
    'j7' => ['boost' => ['fetish_cat', 'rioter_mad']],
  ];

  //サブ役職制限：EASYモード
  public static $chaos_sub_role_limit_easy_list = [
    'decide', 'plague', 'counter_decide', 'dropout', 'good_luck', 'bad_luck', 'authority',
    'reduce_voter', 'upper_voter', 'downer_voter', 'critical_voter', 'random_voter', 'rebel',
    'watcher'
  ];

  //サブ役職制限：NORMALモード
  public static $chaos_sub_role_limit_normal_list = [
    'decide', 'plague', 'counter_decide', 'dropout', 'good_luck', 'bad_luck', 'authority',
    'reduce_voter', 'upper_voter', 'downer_voter', 'critical_voter', 'random_voter', 'rebel',
    'watcher', 'upper_luck', 'downer_luck', 'star', 'disfavor', 'critical_luck', 'random_luck',
    'wisp', 'black_wisp', 'spell_wisp', 'foughten_wisp', 'gold_wisp', 'tengu_spell_wisp'
  ];

  //サブ役職制限：HARDモード
  public static $chaos_sub_role_limit_hard_list = [
    'decide', 'plague', 'counter_decide', 'dropout', 'good_luck', 'bad_luck', 'authority',
    'reduce_voter', 'upper_voter', 'downer_voter', 'critical_voter', 'random_voter', 'rebel',
    'watcher', 'upper_luck', 'downer_luck', 'star', 'disfavor', 'critical_luck', 'random_luck',
    'strong_voice', 'normal_voice', 'weak_voice', 'upper_voice', 'downer_voice', 'inside_voice',
    'outside_voice', 'random_voice', 'mind_open', 'wisp', 'black_wisp', 'spell_wisp',
    'foughten_wisp', 'gold_wisp', 'tengu_spell_wisp'
  ];
}
