<?php
class WeatherList extends ResultList {
  public $prediction_weather_grassy = ['message' => "|スコール|です", 'type' => 'liar'];
  public $prediction_weather_mower = ['message' => "|酸性雨|です", 'type' => 'no_last_words'];
  public $prediction_weather_blind_vote = ['message' => "|晴嵐|です", 'delimiter' => ['|' => 'vote']];
  public $prediction_weather_no_fox_dead = ['message' => "|天気雨|です", 'type' => 'result_mage'];
  public $prediction_weather_critical = ['message' => "|烈日|です", 'type' => 'authority'];
  public $prediction_weather_blind_talk_day = ['message' => "|強風|です", 'type' => 'no_last_words'];
  public $prediction_weather_blind_talk_night = ['message' => "|風雨|です", 'type' => 'no_last_words'];
  public $prediction_weather_full_moon = ['message' => "|満月|です", 'type' => 'result_wolf'];
  public $prediction_weather_new_moon = ['message' => "|新月|です", 'type' => 'result_wolf'];
  public $prediction_weather_no_contact = ['message' => "|花曇|です", 'type' => 'result_wolf'];
  public $prediction_weather_invisible = ['message' => "|黄砂|です", 'type' => 'liar'];
  public $prediction_weather_rainbow = ['message' => "|虹|です", 'type' => 'liar'];
  public $prediction_weather_side_reverse = ['message' => "|ダイヤモンドダスト|です", 'type' => 'liar'];
  public $prediction_weather_line_reverse = ['message' => "|バナナの皮|です", 'type' => 'liar'];
  public $prediction_weather_actor = ['message' => "|スポットライト|です", 'type' => 'liar'];
  public $prediction_weather_critical_luck = ['message' => "|タライ|です", 'type' => 'upper_luck'];
  public $prediction_weather_no_sudden_death = ['message' => "|凪|です", 'type' => 'chicken'];
  public $prediction_weather_thunderbolt = ['message' => "|青天の霹靂|です", 'type' => 'chicken'];
  public $prediction_weather_no_last_words = ['message' => "|涙雨|です", 'type' => 'no_last_words'];
  public $prediction_weather_no_dream = ['message' => "|熱帯夜|です", 'type' => 'result_wolf'];
  public $prediction_weather_full_ogre = ['message' => "|朧月|です", 'type' => 'result_ogre'];
  public $prediction_weather_seal_ogre = ['message' => "|叢雲|です", 'type' => 'result_ogre'];
  public $prediction_weather_full_revive = ['message' => "|雷雨|です", 'type' => 'result_poison_cat'];
  public $prediction_weather_no_revive = ['message' => "|快晴|です", 'type' => 'result_poison_cat'];
  public $prediction_weather_brownie = ['message' => "|慈雨|です", 'type' => 'result_brownie'];
  public $prediction_weather_whisper_ringing = ['message' => "|波風|です", 'type' => 'no_last_words'];
  public $prediction_weather_howl_ringing = ['message' => "|小夜嵐|です", 'type' => 'no_last_words'];
  public $prediction_weather_sweet_ringing = ['message' => "|流星群|です", 'type' => 'no_last_words'];
  public $prediction_weather_deep_sleep = ['message' => "|春時雨|です", 'type' => 'no_last_words'];
  public $prediction_weather_silent = ['message' => "|木漏れ日|です", 'type' => 'no_last_words'];
  public $prediction_weather_missfire_revive = ['message' => "|疎雨|です", 'type' => 'result_poison_cat'];
  public $prediction_weather_no_hunt = ['message' => "|川霧|です", 'type' => 'result_guard'];
  public $prediction_weather_full_guard = ['message' => "|蒼天|です", 'type' => 'result_guard'];
  public $prediction_weather_frostbite = ['message' => "|雪|です", 'type' => 'chicken'];
  public $prediction_weather_alchemy_pharmacist = ['message' => "|梅雨|です", 'type' => 'result_pharmacist'];
  public $prediction_weather_hyper_random_voter = ['message' => "|雹|です", 'type' => 'authority'];
  public $prediction_weather_half_moon = ['message' => "|半月|です", 'type' => 'result_mage'];
  public $prediction_weather_half_guard = ['message' => "|曇天|です", 'type' => 'result_guard'];
  public $prediction_weather_passion = ['message' => "|箒星|です", 'type' => 'liar'];
  public $prediction_weather_no_poison = ['message' => "|旱魃|です", 'type' => 'result_poison'];
  public $prediction_weather_psycho_infected = ['message' => "|濃霧|です", 'type' => 'result_vampire'];
  public $prediction_weather_hyper_critical = ['message' => "|台風|です", 'type' => 'authority'];
  public $prediction_weather_boost_cute = ['message' => "|萌動|です", 'type' => 'no_last_words'];
  public $prediction_weather_no_authority = ['message' => "|蜃気楼|です", 'type' => 'authority'];
  public $prediction_weather_force_assassin_do = ['message' => "|紅月|です", 'type' => 'result_assassin'];
  public $prediction_weather_corpse_courier_mad = ['message' => "|砂塵嵐|です", 'type' => 'result_necromancer'];
  public $prediction_weather_full_wizard = ['message' => "|霧雨|です", 'type' => 'result_wizard'];
  public $prediction_weather_debilitate_wizard = ['message' => "|木枯らし|です", 'type' => 'result_wizard'];
  public $prediction_weather_no_trap = ['message' => "|雪明り|です", 'type' => 'result_wolf'];
  public $prediction_weather_no_sacrifice = ['message' => "|蛍火|です", 'type' => 'result_wolf'];
  public $prediction_weather_no_reflect_assassin = ['message' => "|日蝕|です", 'type' => 'result_assassin'];
  public $prediction_weather_no_cursed = ['message' => "|月蝕|です", 'type' => 'result_mage'];
  public $prediction_weather_blinder = ['message' => "|宵闇|です", 'type' => 'no_last_words'];
  public $prediction_weather_mind_open = ['message' => "|白夜|です", 'type' => 'result_mind_scanner'];
  public $prediction_weather_aurora = ['message' => "|極光|です", 'type' => 'no_last_words'];
  public $prediction_weather_random_step = ['message' => "|霜柱|です", 'delimiter' => ['|' => 'step']];
  public $prediction_weather_no_step = ['message' => "|地吹雪|です", 'delimiter' => ['|' => 'step']];
  public $prediction_weather_confession = ['message' => "|月虹|です", 'type' => 'liar'];
  public $prediction_weather_gentleman = ['message' => "|春一番|です", 'type' => 'liar'];
  public $prediction_weather_lady = ['message' => "|桜吹雪|です", 'type' => 'liar'];
  public $prediction_weather_liar = ['message' => "|宵月|です", 'type' => 'liar'];
  public $prediction_weather_boost_reflect = ['message' => "|寒波|です", 'type' => 'result_assassin'];
  public $prediction_weather_no_cute = ['message' => "|野分|です", 'type' => 'no_last_words'];
  public $prediction_weather_strong_voice = ['message' => "|時化|です", 'type' => 'strong_voice'];
  public $prediction_weather_weak_voice = ['message' => "|細雪|です", 'type' => 'strong_voice'];
  public $prediction_weather_full_tengu = ['message' => "|天狗風|です", 'type' => 'tengu'];
  public $prediction_weather_seal_tengu = ['message' => "|無風|です", 'type' => 'tengu'];
  public $prediction_weather_settle = ['message' => "|彩雲|です", 'delimiter' => ['|' => 'vote']];
  public $prediction_weather_star_fairy = ['message' => "|星空|です", 'type' => 'chiroptera'];
  public $prediction_weather_flower_fairy = ['message' => "|花吹雪|です", 'type' => 'chiroptera'];
  public $prediction_weather_tengu_kill = ['message' => "|白羽の矢|です", 'type' => 'tengu'];
  public $prediction_weather_full_escape = ['message' => "|闇夜|です", 'type' => 'escaper'];
  public $prediction_weather_no_escape = ['message' => "|サーチライト|です", 'type' => 'escaper'];
}
