<?php
class WeatherList extends ResultList {
  public $prediction_weather_grassy = array('message' => "|スコール|です", 'type' => 'liar');
  public $prediction_weather_mower = array('message' => "|酸性雨|です", 'type' => 'no_last_words');
  public $prediction_weather_blind_vote = array('message' => "|晴嵐|です", 'delimiter' => array('|' => 'vote'));
  public $prediction_weather_no_fox_dead = array('message' => "|天気雨|です", 'type' => 'result_mage');
  public $prediction_weather_critical = array('message' => "|烈日|です", 'type' => 'authority');
  public $prediction_weather_blind_talk_day = array('message' => "|強風|です", 'type' => 'no_last_words');
  public $prediction_weather_blind_talk_night = array('message' => "|風雨|です", 'type' => 'no_last_words');
  public $prediction_weather_full_moon = array('message' => "|満月|です", 'type' => 'result_wolf');
  public $prediction_weather_new_moon = array('message' => "|新月|です", 'type' => 'result_wolf');
  public $prediction_weather_no_contact = array('message' => "|花曇|です", 'type' => 'result_wolf');
  public $prediction_weather_invisible = array('message' => "|黄砂|です", 'type' => 'liar');
  public $prediction_weather_rainbow = array('message' => "|虹|です", 'type' => 'liar');
  public $prediction_weather_side_reverse = array('message' => "|ダイヤモンドダスト|です", 'type' => 'liar');
  public $prediction_weather_line_reverse = array('message' => "|バナナの皮|です", 'type' => 'liar');
  public $prediction_weather_actor = array('message' => "|スポットライト|です", 'type' => 'liar');
  public $prediction_weather_critical_luck = array('message' => "|タライ|です", 'type' => 'upper_luck');
  public $prediction_weather_no_sudden_death = array('message' => "|凪|です", 'type' => 'chicken');
  public $prediction_weather_thunderbolt = array('message' => "|青天の霹靂|です", 'type' => 'chicken');
  public $prediction_weather_no_last_words = array('message' => "|涙雨|です", 'type' => 'no_last_words');
  public $prediction_weather_no_dream = array('message' => "|熱帯夜|です", 'type' => 'result_wolf');
  public $prediction_weather_full_ogre = array('message' => "|朧月|です", 'type' => 'result_ogre');
  public $prediction_weather_seal_ogre = array('message' => "|叢雲|です", 'type' => 'result_ogre');
  public $prediction_weather_full_revive = array('message' => "|雷雨|です", 'type' => 'result_poison_cat');
  public $prediction_weather_no_revive = array('message' => "|快晴|です", 'type' => 'result_poison_cat');
  public $prediction_weather_brownie = array('message' => "|慈雨|です", 'type' => 'result_brownie');
  public $prediction_weather_whisper_ringing = array('message' => "|波風|です", 'type' => 'no_last_words');
  public $prediction_weather_howl_ringing = array('message' => "|小夜嵐|です", 'type' => 'no_last_words');
  public $prediction_weather_sweet_ringing = array('message' => "|流星群|です", 'type' => 'no_last_words');
  public $prediction_weather_deep_sleep = array('message' => "|春時雨|です", 'type' => 'no_last_words');
  public $prediction_weather_silent = array('message' => "|木漏れ日|です", 'type' => 'no_last_words');
  public $prediction_weather_missfire_revive = array('message' => "|疎雨|です", 'type' => 'result_poison_cat');
  public $prediction_weather_no_hunt = array('message' => "|川霧|です", 'type' => 'result_guard');
  public $prediction_weather_full_guard = array('message' => "|蒼天|です", 'type' => 'result_guard');
  public $prediction_weather_frostbite = array('message' => "|雪|です", 'type' => 'chicken');
  public $prediction_weather_alchemy_pharmacist = array('message' => "|梅雨|です", 'type' => 'result_pharmacist');
  public $prediction_weather_hyper_random_voter = array('message' => "|雹|です", 'type' => 'authority');
  public $prediction_weather_half_moon = array('message' => "|半月|です", 'type' => 'result_mage');
  public $prediction_weather_half_guard = array('message' => "|曇天|です", 'type' => 'result_guard');
  public $prediction_weather_passion = array('message' => "|箒星|です", 'type' => 'liar');
  public $prediction_weather_no_poison = array('message' => "|旱魃|です", 'type' => 'result_poison');
  public $prediction_weather_psycho_infected = array('message' => "|濃霧|です", 'type' => 'result_vampire');
  public $prediction_weather_hyper_critical = array('message' => "|台風|です", 'type' => 'authority');
  public $prediction_weather_boost_cute = array('message' => "|萌動|です", 'type' => 'no_last_words');
  public $prediction_weather_no_authority = array('message' => "|蜃気楼|です", 'type' => 'authority');
  public $prediction_weather_force_assassin_do = array('message' => "|紅月|です", 'type' => 'result_assassin');
  public $prediction_weather_corpse_courier_mad = array('message' => "|砂塵嵐|です", 'type' => 'result_necromancer');
  public $prediction_weather_full_wizard = array('message' => "|霧雨|です", 'type' => 'result_wizard');
  public $prediction_weather_debilitate_wizard = array('message' => "|木枯らし|です", 'type' => 'result_wizard');
  public $prediction_weather_no_trap = array('message' => "|雪明り|です", 'type' => 'result_wolf');
  public $prediction_weather_no_sacrifice = array('message' => "|蛍火|です", 'type' => 'result_wolf');
  public $prediction_weather_no_reflect_assassin = array('message' => "|日蝕|です", 'type' => 'result_assassin');
  public $prediction_weather_no_cursed = array('message' => "|月蝕|です", 'type' => 'result_mage');
  public $prediction_weather_blinder = array('message' => "|宵闇|です", 'type' => 'no_last_words');
  public $prediction_weather_mind_open = array('message' => "|白夜|です", 'type' => 'result_mind_scanner');
  public $prediction_weather_aurora = array('message' => "|極光|です", 'type' => 'no_last_words');
  public $prediction_weather_random_step = array('message' => "|霜柱|です", 'delimiter' => array('|' => 'step'));
  public $prediction_weather_no_step = array('message' => "|地吹雪|です", 'delimiter' => array('|' => 'step'));
  public $prediction_weather_confession = array('message' => "|月虹|です", 'type' => 'liar');
  public $prediction_weather_gentleman = array('message' => "|春一番|です", 'type' => 'liar');
  public $prediction_weather_lady = array('message' => "|桜吹雪|です", 'type' => 'liar');
  public $prediction_weather_liar = array('message' => "|宵月|です", 'type' => 'liar');
  public $prediction_weather_boost_reflect = array('message' => "|寒波|です", 'type' => 'result_assassin');
  public $prediction_weather_no_cute = array('message' => "|野分|です", 'type' => 'no_last_words');
  public $prediction_weather_strong_voice = array('message' => "|時化|です", 'type' => 'strong_voice');
  public $prediction_weather_weak_voice = array('message' => "|細雪|です", 'type' => 'strong_voice');
  public $prediction_weather_full_tengu = array('message' => "|天狗風|です", 'type' => 'tengu');
  public $prediction_weather_seal_tengu = array('message' => "|無風|です", 'type' => 'tengu');
  public $prediction_weather_settle = array('message' => "|彩雲|です", 'delimiter' => array('|' => 'vote'));
  public $prediction_weather_star_fairy = array('message' => "|星空|です", 'type' => 'chiroptera');
  public $prediction_weather_flower_fairy = array('message' => "|花吹雪|です", 'type' => 'chiroptera');
  public $prediction_weather_tengu_kill = array('message' => "|白羽の矢|です", 'type' => 'tengu');
  public $prediction_weather_full_escape = array('message' => "|闇夜|です", 'type' => 'escaper');
  public $prediction_weather_no_escape = array('message' => "|サーチライト|です", 'type' => 'escaper');
}
